# Generated by Django 4.1.2 on 2022-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='rango_precios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='tipo_comida',
            field=models.CharField(max_length=20),
        ),
    ]
